services:
  - type: web
    name: scasc
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DATABASE_URL
        fromDatabase:
          name: scasc-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true

databases:
  - name: scasc-db
    plan: free